version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "owner"
    assignees:
      - "owner"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
      prefix-scope: "deps"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "owner"
    assignees:
      - "owner"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
      prefix-scope: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
